# generated by datamodel-codegen:
#   filename:  legal-document.schema.json
#   timestamp: 2025-12-27T19:52:22+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class Type(StrEnum):
    """
    Document type
    """

    motion = 'motion'
    response = 'response'
    reply = 'reply'
    order = 'order'
    pleading = 'pleading'
    discovery = 'discovery'


class DocumentMeta(BaseModel):
    documentId: constr(pattern=r'^[0-9A-HJKMNP-TV-Z]{26}$') = Field(
        ..., description='ULID for document'
    )
    caseId: constr(pattern=r'^[0-9A-HJKMNP-TV-Z]{26}$') = Field(
        ..., description='ULID for parent case'
    )
    type: Type = Field(..., description='Document type')
    title: str | None = Field(None, description='Document title')
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class Type1(StrEnum):
    heading = 'heading'
    paragraph = 'paragraph'
    list = 'list'
    signature = 'signature'
    caseblock = 'caseblock'


class HeadingContent(BaseModel):
    text: str
    numbering: str | None = Field(
        None, description="Section numbering like 'I.', 'A.', '1.'"
    )


class Sentence(BaseModel):
    sentenceId: constr(pattern=r'^sent_[a-f0-9]{16}$') = Field(
        ..., description='Content-based hash for stability'
    )
    text: str
    start: int = Field(..., description='Character offset in paragraph')
    end: int = Field(..., description='Character offset in paragraph')


class ListType(StrEnum):
    bullet = 'bullet'
    numbered = 'numbered'
    lettered = 'lettered'


class Item(BaseModel):
    text: str
    marker: str | None = None


class ListContent(BaseModel):
    listType: ListType | None = None
    items: list[Item]


class ParagraphContent(BaseModel):
    text: str = Field(..., description='Plain text content (authoritative)')
    sentences: list[Sentence] | None = None


class Section(BaseModel):
    sectionId: constr(pattern=r'^[0-9A-HJKMNP-TV-Z]{26}$')
    type: Type1
    level: conint(ge=1, le=6)
    content: HeadingContent | ParagraphContent | ListContent | None = None
    children: list[Section] | None = None


class DocumentBody(BaseModel):
    sections: list[Section]


class LegalDocument(BaseModel):
    """
    Canonical legal document format for FACTSWAY platform
    """

    meta: DocumentMeta
    body: DocumentBody


Section.model_rebuild()
